name: build

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: true

  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: test

    steps:
      - run: |
          echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"
        id: metadata

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: v${{ steps.metadata.outputs.version }}
          tag_name: v${{ steps.metadata.outputs.version }}

